name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [opened, synchronize, edited]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    
    - name: Label PR based on title
      if: github.event_name == 'pull_request_target'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const title = context.payload.pull_request.title.toLowerCase();
          const labels = [];
          
          if (title.includes('fix') || title.includes('bug')) {
            labels.push('bug');
          }
          if (title.includes('feat') || title.includes('feature')) {
            labels.push('feature');
          }
          if (title.includes('docs') || title.includes('documentation')) {
            labels.push('documentation');
          }
          if (title.includes('ci') {
            labels.push('ci');
          }
          if (title.includes('aarch64') || title.includes('aarch')) {
            labels.push('aarch64');
          }
          if (title.includes('loongarch64') || title.includes('loongarch')) {
            labels.push('loongarch64');
          }
          if (title.includes('riscv64') || title.includes('riscv')) {
            labels.push('riscv64');
          }
          if (title.includes('x86_64') || title.includes('x86')) {
            labels.push('x86_64');
          }
          
          if (labels.length > 0) {
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labels
            });
          }